Repository AY2122S2-CS2103-F11-1/tp, pull requests merged in 2022-03, with the labels that each got.

#24 Update AboutUs information for Alfred
  docs/AboutUs.md
  docs/images/alfredkohhh.png
Labels: documentation

#23 Update Project Portfolio Page (PPP) for Alfred
  docs/AboutUs.md
  docs/team/alfredkohhh.md
Labels: documentation

#25 Update about us
  docs/AboutUs.md
  docs/images/denniszedead.png
Labels: documentation

#26 Update ppp
  docs/AboutUs.md
  docs/team/denniszedead.md
  docs/team/johndoe.md
Labels: documentation

#29 Add Project Portfolio Page (PPP) for Jun Yang
  docs/team/dannytayjy.md
Labels: documentation

#31 Create PPP for aaron-ljx
  docs/team/aaronljx.md
Labels: documentation

#20 Update Non-Functional Requirements and Glossary in DG
  docs/DeveloperGuide.md
Labels: documentation

#35 Update site-wide settings (.yml file)
  docs/_config.yml
Labels: documentation

#21 Update UserGuide
  docs/UserGuide.md
  docs/images/helpMessage_new.PNG
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#36 Add files via upload
  docs/images/Ui.png
Labels: documentation

#37 Update README.md final
  README.md
Labels: documentation

#38 Update index.md
  docs/index.md
Labels: documentation

#30 Add user profile, value proposition and user stories
  docs/DeveloperGuide.md
Labels: documentation

#40 Updated ReadMe CI Status link to match with our project's CI
  README.md
Labels: documentation

#22 Update Use-Cases in DG
  docs/DeveloperGuide.md
Labels: documentation

#41 Update help message to small png extension
  docs/images/helpMessage_new.png
Labels: documentation

#44 Create base Task class
  src/main/java/seedu/address/tasks/Task.java
Labels: enhancement

#85 Update build gradle settings
  build.gradle
Labels: bug

#91 Branch update task model
  src/main/java/manageezpz/model/task/Date.java
  src/main/java/manageezpz/model/task/Time.java
Labels: bug

#90 Modify List command
  src/main/java/manageezpz/logic/commands/ListCommand.java
  src/main/java/manageezpz/logic/parser/AddressBookParser.java
  src/main/java/manageezpz/logic/parser/ArgumentMultimap.java
  src/main/java/manageezpz/logic/parser/CliSyntax.java
  src/main/java/manageezpz/logic/parser/ListCommandParser.java
  src/main/java/manageezpz/model/AddressBook.java
  src/main/java/manageezpz/model/Model.java
  src/main/java/manageezpz/model/ModelManager.java
  src/main/java/manageezpz/model/task/Date.java
  src/test/java/manageezpz/logic/LogicManagerTest.java
  src/test/java/manageezpz/logic/commands/AddEmployeeCommandTest.java
  src/test/java/manageezpz/logic/commands/CommandTestUtil.java
  src/test/java/manageezpz/logic/commands/ListCommandTest.java
  src/test/java/manageezpz/logic/parser/AddressBookParserTest.java
  src/test/java/manageezpz/logic/parser/ListCommandParserTest.java
Labels: Logic

#96 Find command
  src/main/java/manageezpz/commons/core/Messages.java
  src/main/java/manageezpz/logic/commands/FindCommand.java
  src/main/java/manageezpz/logic/parser/CliSyntax.java
  src/main/java/manageezpz/logic/parser/FindCommandParser.java
  src/main/java/manageezpz/model/ModelManager.java
  src/main/java/manageezpz/model/task/TaskContainsDatePredicate.java
  src/main/java/manageezpz/model/task/TaskContainsKeywordsPredicate.java
  src/test/java/manageezpz/logic/commands/FindCommandTest.java
  src/test/java/manageezpz/logic/parser/AddressBookParserTest.java
  src/test/java/manageezpz/logic/parser/FindCommandParserTest.java
Labels: priority.High, Logic

#132 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/FindTask.puml
  docs/diagrams/List.puml
  docs/images/FindTask.png
  docs/images/List.png
Labels: documentation

#136 Modify list command
  docs/UserGuide.md
  src/main/java/manageezpz/logic/commands/ListCommand.java
  src/main/java/manageezpz/logic/parser/ListCommandParser.java
  src/test/java/manageezpz/logic/commands/CommandTestUtil.java
  src/test/java/manageezpz/logic/commands/DeleteEmployeeCommandTest.java
  src/test/java/manageezpz/logic/commands/EditCommandTest.java
  src/test/java/manageezpz/logic/commands/ListCommandTest.java
  src/test/java/manageezpz/logic/parser/AddressBookParserTest.java
  src/test/java/manageezpz/logic/parser/DeleteEmployeeCommandParserTest.java
  src/test/java/manageezpz/logic/parser/EditCommandParserTest.java
  src/test/java/manageezpz/logic/parser/ListCommandParserTest.java
  src/test/java/manageezpz/logic/parser/ParserUtilTest.java
  src/test/java/manageezpz/testutil/TypicalIndexes.java
Labels: enhancement, priority.High, severity.High

#143 Update ModelManager to Sort task based on priority on start up.
  src/main/java/manageezpz/model/ModelManager.java
Labels: bug

#144 Update Find command
  docs/UserGuide.md
  src/main/java/manageezpz/commons/core/Messages.java
  src/main/java/manageezpz/logic/commands/FindCommand.java
  src/main/java/manageezpz/logic/commands/FindTaskCommand.java
  src/main/java/manageezpz/logic/parser/CliSyntax.java
  src/main/java/manageezpz/logic/parser/FindCommandParser.java
  src/main/java/manageezpz/logic/parser/FindTaskCommandParser.java
  src/main/java/manageezpz/model/task/Task.java
  src/main/java/manageezpz/model/task/TaskContainsDatePredicate.java
  src/main/java/manageezpz/model/task/TaskContainsKeywordsPredicate.java
  src/main/java/manageezpz/model/task/TaskMultiplePredicate.java
  src/test/java/manageezpz/logic/LogicManagerTest.java
  src/test/java/manageezpz/logic/commands/CommandTestUtil.java
  src/test/java/manageezpz/logic/commands/FindCommandTest.java
  src/test/java/manageezpz/logic/commands/FindTaskCommandTest.java
  src/test/java/manageezpz/logic/commands/ListCommandTest.java
  src/test/java/manageezpz/logic/parser/AddressBookParserTest.java
  src/test/java/manageezpz/logic/parser/FindCommandParseTest.java
  src/test/java/manageezpz/logic/parser/FindCommandParserTest.java
  src/test/java/manageezpz/logic/parser/FindTaskCommandParserTest.java
  src/test/java/manageezpz/model/AddressBookTest.java
  src/test/java/manageezpz/model/ModelManagerTest.java
  src/test/java/manageezpz/model/task/TaskTest.java
  src/test/java/manageezpz/model/task/UniqueTaskListTest.java
  src/test/java/manageezpz/testutil/TaskBuilder.java
  src/test/java/manageezpz/testutil/TypicalTasks.java
Labels: enhancement, priority.High

#145 Update Task and Enum for Task
  src/main/java/manageezpz/logic/parser/FindTaskCommandParser.java
  src/main/java/manageezpz/model/task/Priority.java
  src/main/java/manageezpz/model/task/Task.java
  src/main/java/manageezpz/model/task/TaskMultiplePredicate.java
  src/test/java/manageezpz/logic/parser/FindTaskCommandParserTest.java
Labels: enhancement

#156 Abstracting task
  src/main/java/manageezpz/model/task/Deadline.java
  src/main/java/manageezpz/model/task/Event.java
  src/main/java/manageezpz/model/task/Task.java
  src/main/java/manageezpz/model/task/Todo.java
  src/test/java/manageezpz/model/task/TaskTest.java
  src/test/java/manageezpz/testutil/TaskBuilder.java
  src/test/java/manageezpz/testutil/TodoBuilder.java
  src/test/java/manageezpz/testutil/TypicalTasks.java
Labels: enhancement

#165 Remove sort for task.
  src/main/java/manageezpz/model/ModelManager.java
  src/main/java/manageezpz/model/task/Task.java
Labels: bug

#161 Implemented list and find commands for employees and tasks
  build.gradle
  docs/UserGuide.md
  src/main/java/manageezpz/MainApp.java
  src/main/java/manageezpz/logic/commands/FindCommand.java
  src/main/java/manageezpz/logic/commands/FindEmployeeCommand.java
  src/main/java/manageezpz/logic/commands/FindTaskCommand.java
  src/main/java/manageezpz/logic/commands/ListEmployeeCommand.java
  src/main/java/manageezpz/logic/commands/ListTaskCommand.java
  src/main/java/manageezpz/logic/parser/AddressBookParser.java
  src/main/java/manageezpz/logic/parser/CliSyntax.java
  src/main/java/manageezpz/logic/parser/FindCommandParser.java
  src/main/java/manageezpz/logic/parser/FindEmployeeCommandParser.java
  src/main/java/manageezpz/logic/parser/FindTaskCommandParser.java
  src/main/java/manageezpz/logic/parser/ListCommandParser.java
  src/main/java/manageezpz/model/person/NameContainsKeywordsPredicate.java
  src/main/java/manageezpz/model/person/PersonMultiplePredicate.java
  src/main/java/manageezpz/model/task/TaskMultiplePredicate.java
  src/test/java/manageezpz/logic/LogicManagerTest.java
  src/test/java/manageezpz/logic/commands/AddEmployeeCommandIntegrationTest.java
  src/test/java/manageezpz/logic/commands/ClearCommandTest.java
  src/test/java/manageezpz/logic/commands/CommandTestUtil.java
  src/test/java/manageezpz/logic/commands/DeleteEmployeeCommandTest.java
  src/test/java/manageezpz/logic/commands/EditCommandTest.java
  src/test/java/manageezpz/logic/commands/FindEmployeeCommandTest.java
  src/test/java/manageezpz/logic/commands/FindTaskCommandTest.java
  src/test/java/manageezpz/logic/commands/ListEmployeeCommandTest.java
  src/test/java/manageezpz/logic/commands/ListTaskCommandTest.java
  src/test/java/manageezpz/logic/parser/AddressBookParserTest.java
  src/test/java/manageezpz/logic/parser/FindCommandParseTest.java
  src/test/java/manageezpz/logic/parser/FindEmployeeCommandParserTest.java
  src/test/java/manageezpz/logic/parser/FindTaskCommandParserTest.java
  src/test/java/manageezpz/logic/parser/ListCommandParserTest.java
  src/test/java/manageezpz/model/AddressBookTest.java
  src/test/java/manageezpz/model/ModelManagerTest.java
  src/test/java/manageezpz/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/manageezpz/model/person/PersonMultiplePredicateTest.java
  src/test/java/manageezpz/model/task/TaskMultiplePredicateTest.java
  src/test/java/manageezpz/storage/JsonAddressBookStorageTest.java
  src/test/java/manageezpz/storage/JsonSerializableAddressBookTest.java
  src/test/java/manageezpz/storage/StorageManagerTest.java
  src/test/java/manageezpz/testutil/TypicalPersons.java
  src/test/java/manageezpz/testutil/TypicalTasks.java
Labels: documentation, enhancement, severity.High

#168 Finds command error on no specified option
  docs/UserGuide.md
  src/main/java/manageezpz/logic/commands/FindEmployeeCommand.java
  src/main/java/manageezpz/logic/commands/FindTaskCommand.java
  src/main/java/manageezpz/logic/parser/FindEmployeeCommandParser.java
  src/main/java/manageezpz/logic/parser/FindTaskCommandParser.java
  src/main/java/manageezpz/model/person/PersonMultiplePredicate.java
  src/main/java/manageezpz/model/task/TaskMultiplePredicate.java
  src/test/java/manageezpz/logic/commands/FindEmployeeCommandTest.java
  src/test/java/manageezpz/logic/commands/FindTaskCommandTest.java
  src/test/java/manageezpz/logic/parser/FindEmployeeCommandParserTest.java
  src/test/java/manageezpz/logic/parser/FindTaskCommandParserTest.java
  src/test/java/manageezpz/model/person/PersonMultiplePredicateTest.java
  src/test/java/manageezpz/model/task/TaskMultiplePredicateTest.java
Labels: documentation, enhancement, priority.Medium

#181 UI Enhancement
  docs/images/Ui.png
  src/main/java/manageezpz/ui/PersonListPanel.java
  src/main/java/manageezpz/ui/TaskListPanel.java
  src/main/java/manageezpz/ui/UiManager.java
  src/main/resources/images/employee_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: enhancement
