Repository AY2122S2-CS2103-F11-1/tp, pull requests merged in 2022-04, with the labels that each got.

#185 Codes Optimization
  src/main/java/manageezpz/commons/core/Messages.java
  src/main/java/manageezpz/logic/commands/AddDeadlineTaskCommand.java
  src/main/java/manageezpz/logic/commands/AddEventTaskCommand.java
  src/main/java/manageezpz/logic/commands/AddTodoTaskCommand.java
  src/main/java/manageezpz/logic/commands/EditTaskCommand.java
  src/main/java/manageezpz/logic/parser/AddDeadlineTaskCommandParser.java
  src/main/java/manageezpz/logic/parser/AddEmployeeCommandParser.java
  src/main/java/manageezpz/logic/parser/AddEventTaskCommandParser.java
  src/main/java/manageezpz/logic/parser/AddTodoTaskCommandParser.java
  src/main/java/manageezpz/logic/parser/AddressBookParser.java
  src/main/java/manageezpz/logic/parser/DeleteEmployeeCommandParser.java
  src/main/java/manageezpz/logic/parser/DeleteTaskCommandParser.java
  src/main/java/manageezpz/logic/parser/EditEmployeeCommandParser.java
  src/main/java/manageezpz/logic/parser/EditTaskCommandParser.java
  src/main/java/manageezpz/logic/parser/FindEmployeeCommandParser.java
  src/main/java/manageezpz/logic/parser/FindTaskCommandParser.java
  src/main/java/manageezpz/logic/parser/MarkTaskCommandParser.java
  src/main/java/manageezpz/logic/parser/TagTaskCommandParser.java
  src/main/java/manageezpz/logic/parser/TagTaskPriorityCommandParser.java
  src/main/java/manageezpz/logic/parser/UnmarkTaskCommandParser.java
  src/main/java/manageezpz/logic/parser/UntagTaskCommandParser.java
  src/main/java/manageezpz/model/task/Description.java
  src/test/java/manageezpz/logic/parser/AddCommandParserTest.java
  src/test/java/manageezpz/logic/parser/AddressBookParserTest.java
  src/test/java/manageezpz/logic/parser/DeleteEmployeeCommandParserTest.java
  src/test/java/manageezpz/logic/parser/EditCommandParserTest.java
  src/test/java/manageezpz/logic/parser/FindEmployeeCommandParserTest.java
  src/test/java/manageezpz/logic/parser/FindTaskCommandParserTest.java
Labels: bug

#249 Defensive Programming for JSON being modified.
  src/main/java/manageezpz/MainApp.java
  src/main/java/manageezpz/storage/JsonAdaptedTask.java
  src/main/java/manageezpz/storage/JsonSerializableAddressBook.java
Labels: bug

#248 Fix UG inconsistencies and missed details.
  docs/UserGuide.md
  docs/images/helpMessage_new.png
Labels: documentation

#261 Update Jun Yang's PPP
  docs/team/dannytayjy.md
Labels: documentation

#260 Update Alfred's PPP
  docs/team/alfredkohhh.md
Labels: documentation

#258 Update Ng Wen Hao Dennis's PPP
  docs/images/UGFindEmployee.png
  docs/images/UGFindTask.png
  docs/images/UGListEmployee.png
  docs/images/UGListTask.png
  docs/team/denniszedead.md
Labels: documentation

#277 Logger for both find commands
  src/main/java/manageezpz/logic/parser/FindEmployeeCommandParser.java
  src/main/java/manageezpz/logic/parser/FindTaskCommandParser.java
Labels: enhancement

#285 Fix testcases
  src/test/java/manageezpz/logic/commands/FindTaskCommandTest.java
  src/test/java/manageezpz/testutil/TypicalTasks.java
Labels: bug

#289 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/FindTask.puml
  docs/diagrams/FindTaskClassDiagram.puml
  docs/diagrams/FindTaskCommandSequenceDiagram.puml
  docs/diagrams/List.puml
  docs/images/FindTask.png
  docs/images/FindTaskClassDiagram.png
  docs/images/FindTaskCommand.png
  docs/images/FindTaskCommandSequenceDiagram.png
  docs/images/List.png
Labels: documentation

#292 Update DG details and diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UnmarkClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteTask.png
  docs/images/MarkTask.png
  docs/images/UnmarkClassDiagram.png
  docs/images/UnmarkTask.png
Labels: documentation

#300 Update dg
  docs/DeveloperGuide.md
Labels: documentation

#326 Make final updates to UI
  docs/images/Ui.png
  src/main/java/manageezpz/ui/ResultDisplay.java
  src/main/resources/view/DarkTheme.css
Labels: enhancement
